export { default as AboutPage } from './About';
export { default as BlogInfo } from './Bloginfo';
export { default as BlogPage } from './Blog';
export { default as Home } from './Home';
export { default as HtmlTemplates } from './Html-templates';
export { default as ServicesPage } from './Services';
export { default as WorksPage } from './Works';
export { default as Htmlinfo } from './Htmlinfo';
export { default as PortfolioInfo } from './PortfolioInfo';
export { default as Contact } from './Contact'
export { default as Page404 } from './Page404'
export { default as MaintenancePage } from './MaintenancePage'