export { default as About } from './About';
export { default as Blog } from './Blog';
export { default as Faq } from './Faq';
export { default as Footer } from './Footer';
export { default as Header } from './Header';
export { default as Work } from './Work';
export { default as Hero } from './Hero';
export { default as Inner } from './Inner';
export { default as ServicesLine } from './ServicesLine';
export { default as Services } from './Services';
export { default as Skills } from './Skills';
export { default as Bio } from './Bio';
export { default as BlogContent } from './BlogContent';
export { default as BlogPageContent } from './BlogPageContent'
export { default as Portfolio } from './Portfolio'
